name: Check PR
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

permissions: {}

jobs:
  check-pr:
    uses: quotidian-ennui/workflows-olio/.github/workflows/check-pr-with-trigger.yml@6099af4157e6653a07431f39552a6b36bb331d2b # v2.1.0
    permissions:
      contents: write
      pull-requests: write
      checks: write
