name: Check PR
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

permissions: {}

jobs:
  check-pr:
    uses: quotidian-ennui/workflows-olio/.github/workflows/check-pr-with-trigger.yml@d1d56e91660ddd4d83ff65054d4d6efc5adfc77b # v2.2.5
    permissions:
      contents: write
      pull-requests: write
      checks: write
